### PR TITLE
fix: update first two cells of notebooks

### PR DESCRIPTION
**Pull request by victor-wildlife**
I added a roadblock to restart the colab session if panoptes can't be imported, this avoids issues with the requests packages. I also got rid of the code to fix libmagic issues as it seems no longer needed, this was initially added to deal with panoptes issues. I combined the installation requirements into the first notebook cell and left the second cell to only load packages. I added a small description before the first cell for colab users

### CODE REVIEW

**Review by Diewertje11 — APPROVED** [review]
Looks really good, and the commit message gives a clear description of the changes. 
The only change I don't understand is why you changed:
sys.path.append("..") to sys.path.append(os.path.abspath(".."))
Because I think that it should do the same. 

And black should be run on the files. After that, it has my approaval!

**Comment by Diewertje11** [comment]
We talked about the sys.path and we decided to change it to 

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))

This still needs to be changed.

**Comment by victor-wildlife** [comment]
@jannesgg all good on your end to merge these changes?

**Review by jannesgg — COMMENTED** [review]
Looks good!

**Pull request merged**
